name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Compile scripts
        run: python -m compileall scripts
      - name: Validate offline snapshot flow
        run: python scripts/validate_repo.py --hero varus --input-dir snapshots/varus --offline
